[config]
schemaVersion = "0.0.1"

[package]
namespace = "F_thx"
name = "I18nCN"
versionNumber = "1.2.6.2"
description = "Translate the mod, translate all mods into Chinese "
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./ts-build"

[publish]
repository = "https://thunderstore.io"
communities = [ "cities-skylines-ii", ]
categories = [ "mods" ]